/**
 * Embed the built Lore UI (packages/ui/dist, produced by Vite) into the
 * gateway as a generated TypeScript module, src/ui-assets.generated.ts.
 *
 * Embedding — rather than copying files next to the bundle — means every
 * gateway artifact serves the exact same SPA with zero filesystem access at
 * request time: the npm CJS bundle (dist/index.cjs), the Bun ESM bundle used
 * in-process by @loreai/opencode, the Node SEA binaries, and a plain
 * `tsx src/index.ts` dev checkout. The generated module is git-ignored and
 * (re)generated by script/build.ts, script/bundle.ts and build-binary-sea.ts.
 *
 * Text assets are stored as UTF-8 string literals, binary assets as base64.
 * Vite content-hashes everything under dist/assets/, so the gateway can serve
 * that directory with immutable caching; index.html is served no-cache.
 *
 * Compressible text assets additionally carry precompressed variants (zstd,
 * brotli, gzip — each at its maximum setting, base64) so the gateway can
 * negotiate `Accept-Encoding` without compressing at request time. A variant
 * is dropped when it is not smaller than the identity bytes; zstd is skipped
 * with a warning on Node builds without `zlib.zstdCompressSync`.
 */
import { createHash } from "node:crypto";
import {
  existsSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { dirname, extname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as zlib from "node:zlib";

const here = dirname(fileURLToPath(import.meta.url));
const packageDir = dirname(here);
const repoRoot = dirname(dirname(packageDir));
const uiDir = join(repoRoot, "packages", "ui");
const uiDistDir = join(uiDir, "dist");

export const GENERATED_MODULE = join(
  packageDir,
  "src",
  "ui-assets.generated.ts",
);

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".txt": "text/plain; charset=utf-8",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

const TEXT_EXTENSIONS = new Set([
  ".html",
  ".js",
  ".mjs",
  ".css",
  ".json",
  ".webmanifest",
  ".map",
  ".svg",
  ".txt",
]);

/** Assets worth precompressing; fonts and images are already compressed. */
const COMPRESSIBLE_EXTENSIONS = new Set([
  ".html",
  ".js",
  ".mjs",
  ".css",
  ".json",
  ".webmanifest",
  ".svg",
]);

export type UiContentEncoding = "zstd" | "br" | "gzip";
export const UI_CONTENT_ENCODINGS: readonly UiContentEncoding[] = [
  "zstd",
  "br",
  "gzip",
];

type Compressor = (buf: Buffer) => Buffer;
/** zstd's "ultra" ceiling (`zstd --ultra -22`); Node exposes no constant for it. */
const ZSTD_MAX_LEVEL = 22;

function compressors(
  warn: (message: string) => void,
): Map<UiContentEncoding, Compressor> {
  const out = new Map<UiContentEncoding, Compressor>();
  // Node < 22.15 / 23.8 has no zstd bindings; the build still succeeds and
  // the gateway simply never offers `Content-Encoding: zstd`.
  if (typeof zlib.zstdCompressSync === "function") {
    out.set("zstd", (buf) =>
      zlib.zstdCompressSync(buf, {
        params: { [zlib.constants.ZSTD_c_compressionLevel]: ZSTD_MAX_LEVEL },
      }),
    );
  } else {
    warn(
      `ui-assets: zlib.zstdCompressSync is unavailable on ${process.version}; skipping zstd variants`,
    );
  }
  out.set("br", (buf) =>
    zlib.brotliCompressSync(buf, {
      params: {
        [zlib.constants.BROTLI_PARAM_QUALITY]:
          zlib.constants.BROTLI_MAX_QUALITY,
        [zlib.constants.BROTLI_PARAM_MODE]: zlib.constants.BROTLI_MODE_TEXT,
        [zlib.constants.BROTLI_PARAM_SIZE_HINT]: buf.byteLength,
      },
    }),
  );
  out.set("gzip", (buf) => zlib.gzipSync(buf, { level: 9 }));
  return out;
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function runViteBuild(): void {
  const require = createRequire(join(uiDir, "package.json"));
  // vite's package exports do not expose its bin; go through package.json.
  const vitePkgPath = require.resolve("vite/package.json");
  const vitePkg = JSON.parse(readFileSync(vitePkgPath, "utf8")) as {
    bin: string | Record<string, string>;
  };
  const binRel =
    typeof vitePkg.bin === "string" ? vitePkg.bin : vitePkg.bin["vite"];
  if (!binRel) throw new Error("vite package.json has no bin entry");
  const viteBin = join(dirname(vitePkgPath), binRel);
  const result = spawnSync(process.execPath, [viteBin, "build"], {
    cwd: uiDir,
    stdio: "inherit",
  });
  if (result.status !== 0) {
    throw new Error(`Lore UI build failed (exit ${result.status ?? "signal"})`);
  }
}

export interface UiAssetsResult {
  files: number;
  bytes: number;
  buildId: string | null;
  /** Per-file sizes: identity plus every emitted precompressed variant. */
  sizes: UiAssetSizes[];
}

export interface UiAssetSizes {
  path: string;
  identity: number;
  variants: Partial<Record<UiContentEncoding, number>>;
}

/**
 * Generate src/ui-assets.generated.ts.
 *
 * - `build: "always"`     — run the Vite build first (bundle / binary builds).
 * - `build: "if-missing"` — run it only when packages/ui/dist has no
 *                            index.html (dev shim build / postinstall).
 * - `build: "never"`      — embed whatever is on disk; an empty manifest when
 *                            nothing was built (the gateway then answers
 *                            /ui with 503 instead of failing to import).
 */
export function generateUiAssetsModule(
  opts: { build: "always" | "if-missing" | "never" } = { build: "never" },
): UiAssetsResult {
  const hasBuild = existsSync(join(uiDistDir, "index.html"));
  if (opts.build === "always" || (opts.build === "if-missing" && !hasBuild)) {
    runViteBuild();
  }

  const entries: string[] = [];
  const digest = createHash("sha256");
  const sizes: UiAssetSizes[] = [];
  let bytes = 0;
  let files = 0;

  if (existsSync(join(uiDistDir, "index.html"))) {
    const compress = compressors((message) => console.warn(message));
    for (const full of walk(uiDistDir)) {
      const rel = relative(uiDistDir, full).split("\\").join("/");
      const ext = extname(full).toLowerCase();
      const contentType = CONTENT_TYPES[ext] ?? "application/octet-stream";
      const buf = readFileSync(full);
      // The build ID covers identity bytes only, so it is stable across build
      // hosts with and without zstd support.
      digest.update(rel).update("\0").update(buf);
      bytes += buf.byteLength;
      files++;
      const encoding = TEXT_EXTENSIONS.has(ext) ? "utf8" : "base64";
      const data =
        encoding === "utf8" ? buf.toString("utf8") : buf.toString("base64");
      const variants: string[] = [];
      const variantSizes: UiAssetSizes["variants"] = {};
      if (COMPRESSIBLE_EXTENSIONS.has(ext)) {
        for (const [name, fn] of compress) {
          const compressed = fn(buf);
          if (compressed.byteLength >= buf.byteLength) continue;
          variantSizes[name] = compressed.byteLength;
          variants.push(
            `[${JSON.stringify(name)}, ${JSON.stringify(compressed.toString("base64"))}]`,
          );
        }
      }
      sizes.push({
        path: rel,
        identity: buf.byteLength,
        variants: variantSizes,
      });
      entries.push(
        `  [${JSON.stringify(rel)}, ${JSON.stringify(contentType)}, ${JSON.stringify(encoding)}, ${JSON.stringify(data)}, [${variants.join(", ")}]],`,
      );
    }
  }

  const buildId = files > 0 ? digest.digest("hex").slice(0, 16) : null;
  const source = [
    "// Generated by packages/gateway/script/ui-assets.ts from packages/ui/dist — do not edit.",
    "// Rebuilt by `pnpm --filter @loreai/gateway build` / `bundle`; git-ignored.",
    "/* oxlint-disable */",
    "",
    'export type UiAssetEncoding = "utf8" | "base64";',
    'export type UiContentEncoding = "zstd" | "br" | "gzip";',
    "",
    "/** [content encoding, base64 of the precompressed bytes] */",
    "export type UiAssetVariant = readonly [",
    "  contentEncoding: UiContentEncoding,",
    "  base64: string,",
    "];",
    "",
    "/** [relative path under /ui/, content type, encoding, data, precompressed variants] */",
    "export type UiAssetRecord = readonly [",
    "  path: string,",
    "  contentType: string,",
    "  encoding: UiAssetEncoding,",
    "  data: string,",
    "  variants: readonly UiAssetVariant[],",
    "];",
    "",
    `export const UI_BUILD_ID: string | null = ${JSON.stringify(buildId)};`,
    "",
    "export const UI_ASSET_FILES: readonly UiAssetRecord[] = [",
    ...entries,
    "];",
    "",
  ].join("\n");

  writeFileSync(GENERATED_MODULE, source);
  return { files, bytes, buildId, sizes };
}

export function describeUiAssets(result: UiAssetsResult): string {
  if (result.files === 0) {
    return "ui-assets.generated.ts: empty manifest (packages/ui not built)";
  }
  const total = (name: UiContentEncoding) =>
    result.sizes.reduce((sum, s) => sum + (s.variants[name] ?? s.identity), 0);
  const kib = (n: number) => `${(n / 1024).toFixed(1)} KiB`;
  return `ui-assets.generated.ts: ${result.files} files, ${kib(result.bytes)} identity (zstd ${kib(total("zstd"))}, br ${kib(total("br"))}, gzip ${kib(total("gzip"))}), build ${result.buildId}`;
}

/** Markdown size table (identity / zstd / br / gzip per file), for PR bodies. */
export function formatUiAssetSizeTable(result: UiAssetsResult): string {
  const bytes = (n: number) => `${n.toLocaleString("en-US")} B`;
  const cell = (n: number | undefined, identity: number) =>
    n === undefined
      ? "—"
      : `${bytes(n)} (${Math.round((n / identity) * 100)} %)`;
  const rows = result.sizes
    .filter((s) => Object.keys(s.variants).length > 0)
    .map(
      (s) =>
        `| \`${s.path}\` | ${bytes(s.identity)} | ${cell(s.variants.zstd, s.identity)} | ${cell(s.variants.br, s.identity)} | ${cell(s.variants.gzip, s.identity)} |`,
    );
  return [
    "| Asset | identity | zstd | br | gzip |",
    "|---|---|---|---|---|",
    ...rows,
  ].join("\n");
}

/**
 * Make sure the generated module exists so `tsc`/vitest can resolve the
 * import even on a checkout that has never built the UI. Never overwrites an
 * existing manifest.
 */
export function ensureUiAssetsModule(): void {
  if (existsSync(GENERATED_MODULE)) return;
  generateUiAssetsModule({ build: "never" });
}

if (
  process.argv[1] &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1])
) {
  const mode = process.argv[2] ?? "--ensure";
  if (mode === "--ensure") {
    ensureUiAssetsModule();
  } else if (mode === "--build") {
    const result = generateUiAssetsModule({ build: "always" });
    console.log(describeUiAssets(result));
  } else if (mode === "--sizes") {
    const result = generateUiAssetsModule({ build: "never" });
    console.log(formatUiAssetSizeTable(result));
  } else {
    console.error(
      `usage: tsx script/ui-assets.ts [--ensure | --build | --sizes]`,
    );
    process.exit(2);
  }
}
