/**
 * Embed the built Lore UI (packages/ui/dist, produced by Vite) into the
 * gateway as a generated TypeScript module, src/ui-assets.generated.ts.
 *
 * Embedding — rather than copying files next to the bundle — means every
 * gateway artifact serves the exact same SPA with zero filesystem access at
 * request time: the npm CJS bundle (dist/index.cjs), the Bun ESM bundle used
 * in-process by @loreai/opencode, the Node SEA binaries, and a plain
 * `tsx src/index.ts` dev checkout. The generated module is git-ignored and
 * (re)generated by script/build.ts, script/bundle.ts and build-binary-sea.ts.
 *
 * Text assets are stored as UTF-8 string literals, binary assets as base64.
 * Vite content-hashes everything under dist/assets/, so the gateway can serve
 * that directory with immutable caching; index.html is served no-cache.
 */
import { createHash } from "node:crypto";
import {
  existsSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { dirname, extname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageDir = dirname(here);
const repoRoot = dirname(dirname(packageDir));
const uiDir = join(repoRoot, "packages", "ui");
const uiDistDir = join(uiDir, "dist");

export const GENERATED_MODULE = join(
  packageDir,
  "src",
  "ui-assets.generated.ts",
);

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".txt": "text/plain; charset=utf-8",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

const TEXT_EXTENSIONS = new Set([
  ".html",
  ".js",
  ".mjs",
  ".css",
  ".json",
  ".webmanifest",
  ".map",
  ".svg",
  ".txt",
]);

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function runViteBuild(): void {
  const require = createRequire(join(uiDir, "package.json"));
  // vite's package exports do not expose its bin; go through package.json.
  const vitePkgPath = require.resolve("vite/package.json");
  const vitePkg = JSON.parse(readFileSync(vitePkgPath, "utf8")) as {
    bin: string | Record<string, string>;
  };
  const binRel =
    typeof vitePkg.bin === "string" ? vitePkg.bin : vitePkg.bin["vite"];
  if (!binRel) throw new Error("vite package.json has no bin entry");
  const viteBin = join(dirname(vitePkgPath), binRel);
  const result = spawnSync(process.execPath, [viteBin, "build"], {
    cwd: uiDir,
    stdio: "inherit",
  });
  if (result.status !== 0) {
    throw new Error(`Lore UI build failed (exit ${result.status ?? "signal"})`);
  }
}

export interface UiAssetsResult {
  files: number;
  bytes: number;
  buildId: string | null;
}

/**
 * Generate src/ui-assets.generated.ts.
 *
 * - `build: "always"`     — run the Vite build first (bundle / binary builds).
 * - `build: "if-missing"` — run it only when packages/ui/dist has no
 *                            index.html (dev shim build / postinstall).
 * - `build: "never"`      — embed whatever is on disk; an empty manifest when
 *                            nothing was built (the gateway then answers
 *                            /ui with 503 instead of failing to import).
 */
export function generateUiAssetsModule(
  opts: { build: "always" | "if-missing" | "never" } = { build: "never" },
): UiAssetsResult {
  const hasBuild = existsSync(join(uiDistDir, "index.html"));
  if (opts.build === "always" || (opts.build === "if-missing" && !hasBuild)) {
    runViteBuild();
  }

  const entries: string[] = [];
  const digest = createHash("sha256");
  let bytes = 0;
  let files = 0;

  if (existsSync(join(uiDistDir, "index.html"))) {
    for (const full of walk(uiDistDir)) {
      const rel = relative(uiDistDir, full).split("\\").join("/");
      const ext = extname(full).toLowerCase();
      const contentType = CONTENT_TYPES[ext] ?? "application/octet-stream";
      const buf = readFileSync(full);
      digest.update(rel).update("\0").update(buf);
      bytes += buf.byteLength;
      files++;
      const encoding = TEXT_EXTENSIONS.has(ext) ? "utf8" : "base64";
      const data =
        encoding === "utf8" ? buf.toString("utf8") : buf.toString("base64");
      entries.push(
        `  [${JSON.stringify(rel)}, ${JSON.stringify(contentType)}, ${JSON.stringify(encoding)}, ${JSON.stringify(data)}],`,
      );
    }
  }

  const buildId = files > 0 ? digest.digest("hex").slice(0, 16) : null;
  const source = [
    "// Generated by packages/gateway/script/ui-assets.ts from packages/ui/dist — do not edit.",
    "// Rebuilt by `pnpm --filter @loreai/gateway build` / `bundle`; git-ignored.",
    "/* oxlint-disable */",
    "",
    'export type UiAssetEncoding = "utf8" | "base64";',
    "",
    "/** [relative path under /ui/, content type, encoding, data] */",
    "export type UiAssetRecord = readonly [",
    "  path: string,",
    "  contentType: string,",
    "  encoding: UiAssetEncoding,",
    "  data: string,",
    "];",
    "",
    `export const UI_BUILD_ID: string | null = ${JSON.stringify(buildId)};`,
    "",
    "export const UI_ASSET_FILES: readonly UiAssetRecord[] = [",
    ...entries,
    "];",
    "",
  ].join("\n");

  writeFileSync(GENERATED_MODULE, source);
  return { files, bytes, buildId };
}

export function describeUiAssets(result: UiAssetsResult): string {
  if (result.files === 0) {
    return "ui-assets.generated.ts: empty manifest (packages/ui not built)";
  }
  return `ui-assets.generated.ts: ${result.files} files, ${(result.bytes / 1024).toFixed(1)} KiB, build ${result.buildId}`;
}

/**
 * Make sure the generated module exists so `tsc`/vitest can resolve the
 * import even on a checkout that has never built the UI. Never overwrites an
 * existing manifest.
 */
export function ensureUiAssetsModule(): void {
  if (existsSync(GENERATED_MODULE)) return;
  generateUiAssetsModule({ build: "never" });
}

if (
  process.argv[1] &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1])
) {
  const mode = process.argv[2] ?? "--ensure";
  if (mode === "--ensure") {
    ensureUiAssetsModule();
  } else if (mode === "--build") {
    console.log(describeUiAssets(generateUiAssetsModule({ build: "always" })));
  } else {
    console.error(`usage: tsx script/ui-assets.ts [--ensure | --build]`);
    process.exit(2);
  }
}
