/**
 * Node parseArgs schema shared by the legacy CLI dispatcher and the minimal
 * gateway supervisor. Keep this module dependency-free so the supervisor can
 * identify `start` without loading the gateway runtime.
 */
export const LEGACY_OPTIONS = {
  port: { type: "string" as const, short: "p" },
  host: { type: "string" as const, short: "H", multiple: true },
  debug: { type: "boolean" as const, short: "d" },
  remote: { type: "string" as const, short: "r" },
  version: { type: "boolean" as const, short: "v" },
  help: { type: "boolean" as const, short: "h" },
  yes: { type: "boolean" as const, short: "y" },
  interactive: { type: "boolean" as const, short: "i" },
  noPlugin: { type: "boolean" as const },
  follow: { type: "boolean" as const, short: "f" },
  n: { type: "string" as const },
  lines: { type: "string" as const },
  path: { type: "boolean" as const },
  to: { type: "string" as const },
  project: { type: "string" as const },
  limit: { type: "string" as const },
  json: { type: "boolean" as const },
  base: { type: "string" as const },
  head: { type: "string" as const },
  model: { type: "string" as const },
  effort: { type: "string" as const },
  "import-lore-md": { type: "boolean" as const },
  gate: { type: "boolean" as const },
  "dry-run": { type: "boolean" as const },
  purge: { type: "boolean" as const },
  "no-children": { type: "boolean" as const },
  "no-worktrees": { type: "boolean" as const },
  agent: { type: "string" as const },
  file: { type: "string" as const },
  source: { type: "string" as const },
  global: { type: "boolean" as const },
  "mem0-qdrant": { type: "string" as const },
  "mem0-collection": { type: "string" as const },
  "mem0-server": { type: "string" as const },
  "mem0-token": { type: "string" as const },
  "mem0-path": { type: "string" as const },
  "mem0-user": { type: "string" as const },
  "min-confidence": { type: "string" as const },
  "no-backup": { type: "boolean" as const },
  knowledge: { type: "boolean" as const },
  temporal: { type: "boolean" as const },
  distillations: { type: "boolean" as const },
  all: { type: "boolean" as const },
  local: { type: "boolean" as const, short: "l" },
  bg: { type: "boolean" as const },
  daemon: { type: "boolean" as const },
  "allow-remote-management": { type: "boolean" as const },
  email: { type: "string" as const },
  role: { type: "string" as const },
  offline: { type: "boolean" as const },
  invite: { type: "string" as const },
  verify: { type: "boolean" as const },
  "no-browser": { type: "boolean" as const },
  "print-vendor-info": { type: "boolean" as const },
  "check-embeddings": { type: "boolean" as const },
  "check-vec": { type: "boolean" as const },
  "check-read-offload": { type: "boolean" as const },
} as const;
